---
framework: mocha
preRun:
     command:
        - npm install
preMerge:
  pattern:
    - "./build/test/test-*.js"
postMerge: 
  pattern: 
    - "./build/test/test-*.js"
postRun:
     command:
        - node --version
version: 1.0
