import synthtool as s
import synthtool.gcp as gcp
import logging
logging.basicConfig(level=logging.DEBUG)
common_templates = gcp.CommonTemplates()
templates = common_templates.node_library()
s.copy(templates, excludes=[
  '.eslintignore',
  '.eslintrc.yml',
  '.github/ISSUE_TEMPLATE/bug_report.md',
  '.github/ISSUE_TEMPLATE/feature_request.md',
  '.github/ISSUE_TEMPLATE/support_request.md',
  '.jsdoc.js',
  '.kokoro/common.cfg',
  '.kokoro/continuous/node10/common.cfg',
  '.kokoro/continuous/node10/docs.cfg',
  '.kokoro/continuous/node10/lint.cfg',
  '.kokoro/continuous/node10/samples-test.cfg',
  '.kokoro/continuous/node10/system-test-grpcjs.cfg',
  '.kokoro/continuous/node10/system-test.cfg',
  '.kokoro/continuous/node10/test.cfg',
  '.kokoro/continuous/node11/common.cfg',
  '.kokoro/continuous/node11/test.cfg',
  '.kokoro/continuous/node6/common.cfg',
  '.kokoro/continuous/node6/test.cfg',
  '.kokoro/continuous/node8/common.cfg',
  '.kokoro/continuous/node8/test.cfg',
  '.kokoro/docs.sh',
  '.kokoro/lint.sh',
  '.kokoro/presubmit/node10/common.cfg',
  '.kokoro/presubmit/node10/docs.cfg',
  '.kokoro/presubmit/node10/lint.cfg',
  '.kokoro/presubmit/node10/samples-test.cfg',
  '.kokoro/presubmit/node10/system-test-grpcjs.cfg',
  '.kokoro/presubmit/node10/system-test.cfg',
  '.kokoro/presubmit/node10/test.cfg',
  '.kokoro/presubmit/node11/common.cfg',
  '.kokoro/presubmit/node11/test.cfg',
  '.kokoro/presubmit/node6/common.cfg',
  '.kokoro/presubmit/node6/test.cfg',
  '.kokoro/presubmit/node8/common.cfg',
  '.kokoro/presubmit/node8/test.cfg',
  '.kokoro/publish.sh',
  '.kokoro/release/publish.cfg',
  '.kokoro/samples-test.sh',
  '.kokoro/system-test.sh',
  '.kokoro/test.bat',
  '.kokoro/test.sh',
  '.kokoro/trampoline.sh',
  '.nycrc',
  '.prettierignore',
  '.prettierrc',
  'CODE_OF_CONDUCT.md',
  'CONTRIBUTING.md',
  'LICENSE',
  'Skipping: README.md',
  'codecov.yaml',
  'renovate.json'
])
