on:
  release:
    types: [published]
name: release
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: 'https://wombat-dressing-room.appspot.com'
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
